[package]
name = "libmaxminddb-rs-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
libmaxminddb-rs = { path = "..", default-features = false, features = ["reader", "simd"] }

[[bin]]
name = "reader_from_bytes"
path = "fuzz_targets/reader_from_bytes.rs"
test = false
doc = false
bench = false

[workspace]
